x = 4
y = 3

sum = x+y
print(f"{x} + {y} = {sum}")
sub = x-y
print(f"{x} - {y} = {sub}")
mult = x*y
print(f"{x} x {y} = {mult}")
div = x/y
print(f"{x} / {y} = {div}")
remainder = x%y
print(f"{x} % {y} = {remainder}")
quoc = x//y
print(f"{x} // {y} = {quoc}")
inc = x+1
print(f"{x}++ = {inc}")
dec = y-1
print(f"{y}-- = {dec}")